global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
  - job_name: 'auth-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['auth-service:8081']
  - job_name: 'reporting-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['reporting-service:8082']
